### ISSUE TITLE
Small GUI input box bug

### ISSUE THREAD

**Issue by kavanase** [ertekin-research-group/VTAnDeM#2]
Hi @mathtoriyama!
Nice to get to say hello in person last week 😄 
This is quite a nice and useful package, and a lot of careful work clearly went into it 💪 

One tiny issue I ran into when using the GUI with one of the examples, for some reason the `T_syn` box wouldn't let me click into it and add a value, but I was able to do this with all the other GUI input boxes. Probably an easy fix!
![image](https://user-images.githubusercontent.com/51478689/205649223-a4117309-f364-431b-afe7-01b5b20ae267.png)

**Comment by mathtoriyama** [comment]
Thanks for catching this @kavanase! This should be fixed now.
